echo "
Put this in your .bashrc or similar:


export TEEES_FLASK_SECRET_KEY=lasdfGFJKSAJSFGDSAKJFDG
export TEEES_DEV_ENVIRON=True
export TEEES_STRIPE_SECRET_KEY=
export TEEES_STRIPE_PUBLISHABLE_KEY=
export TEEES_MYSQL_PW=
export TEEES_SSL_LOCATION=
"
